---
- hosts: localhost
  vars:
    gri_installs:
      - repo: buildpacks/pack
        archive_extension: tgz
        archive_key: pack
        checksum_key: pack
        separator: '-'
        tag: v0.34.2
  roles:
    - role: bradfordwagner.go-releaser-install
  tasks:
    - name: smoketest installed binaries are added to path
      command: "{{ item }}"
      loop:
       - pack -h
